
TOKEN(TK_NONE),
TOKEN(TK_SPACE),
TOKEN(TK_COMMENT),
TOKEN(TK_STRING),
TOKEN(TK_ID),
TOKEN(TK_MISC),
TOKEN(TK_SEMI_COLON),
TOKEN(TK_OPEN_BLOCK),
TOKEN(TK_CLOSE_BLOCK),
TOKEN(TK_UNKNOWN),
TOKEN(TK_EOF),

